theme: jekyll-theme-cayman
title: Welcome to Fuzzy Pug Cup, Online Chess Tournament
description: This tournament is open for all age players, reagrdless of skill, religion, height, weight, political orientation 
